# Sentiment Analysis

In [1]:
!pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\kftsu\anaconda3\lib\site-packages (0.21.0)

In [2]:
from dotenv import dotenv_values

config = dotenv_values('.env')

In [3]:
!pip install requests

Requirement already satisfied: requests in c:\users\kftsu\anaconda3\lib\site-packages (2.25.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kftsu\anaconda3\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kftsu\anaconda3\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<3,>=2.5 in c:\users\kftsu\anaconda3\lib\site-packages (from requests) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\users\kftsu\anaconda3\lib\site-packages (from requests) (3.0.4)

In [4]:
import requests
import json

In [5]:
bearer_token = config["BEARER_TOKEN"]

search_url = "https://api.twitter.com/2/tweets/search/recent"

query_params = {
    'query' : "\"Cow\"Ireland -is:retweet",
    'max_results' : '50',
    'tweet.fields': 'author_id',
    'user.fields': 'name'
}

def bearer_oauth(r):
    r.headers["Authorization"] = f"Bearer {bearer_token}"
    r.headers["User-Agent"] = "v2RecentSearchPython"
    return r

def connect_to_endpoint(url, params):
    response = requests.get(url, auth=bearer_oauth, params=params)
    response.status_code
    return response.json()

json_response = connect_to_endpoint(search_url, query_params)

parsedRes = json.dumps(json_response, indent=3, ensure_ascii=False)
print(parsedRes)

{
   "data": [
      {
         "edit_history_tweet_ids": [
            "1607719593497305089"
         ],
         "text": "It is understood a cow was trapped in a slurry pit https://t.co/gU5HZgU3Vt",
         "id": "1607719593497305089",
         "author_id": "20687723"
      },
      {
         "edit_history_tweet_ids": [
            "1607698163133038594"
         ],
         "text": "You know you're down home when you're having pints and you end up buying a raffle ticket for the local hurling club where the game is they grid out the pitch and wait for a cow to shite in the winning square. Lovely hurling @Craobh_Rua\n\n#GAA #Ireland #Armagh #Greatdayfortheparish",
         "id": "1607698163133038594",
         "author_id": "431813199"
      },
      {
         "edit_history_tweet_ids": [
            "1606886570044309504"
         ],
         "text": "Always. In 5th or 6th grade I did a school report on English genocide of Ireland, presenting on unfair laws. E.g. Irish peasants had to sell any cow that became worth more than a certain amount to the Brits, but at a mandated low price so Irish farmers could never accrue wealth. https://t.co/R4i98dOLLM",
         "id": "1606886570044309504",
         "author_id": "17845980"
      },
      {
         "edit_history_tweet_ids": [
            "1606438931540606978"
         ],
         "text": "@7YRBitchLasagna @JenCages @MucusMucous @ADouble777 @TomDoubting @fastcow33 @RepublicanRehab @atriana @michellmybell1 @Bruh50347166 @BigBrotherNut @TreatHunterDog @shrekvivre @CivilLost @SnoJusticeCuz @BidenTour @42Gnome @kimmsue70 @RealDoctorT @cl1ntonserver @lemmabarkaloo @NewfMom29 @NotaDorR1 @TruthPyRate @ADirtyRottenDog @pookietooth @odktiger @Evry1H8sGrtzLOL @TastyMorsel6 @MurphyYuiko @theProgEqualist @LeAidan098 @1717mule @Polt223 @Jennie_SC1 @FemmeVoilet @LucaBra66424748 @_Kel_Varnsen_ @JackWhoElse @429jamesowens @instinctnaturel @Timeforfreespe1 @cow_cousin @MyChickenDinner @VtTbQW9s3xjPOow @TwoSides1Truth @SomeSis1 @LadyOfTheOcean1 @SnoJusticeBro @Aimhighffw My clan is in Ireland.  Small world.",
         "id": "1606438931540606978",
         "author_id": "1300278104485756928"
      },
      {
         "edit_history_tweet_ids": [
            "1606437397582979073"
         ],
         "text": "@JenCages @MucusMucous @RedStateJimy @ADouble777 @TomDoubting @fastcow33 @RepublicanRehab @atriana @michellmybell1 @Bruh50347166 @BigBrotherNut @TreatHunterDog @shrekvivre @CivilLost @SnoJusticeCuz @BidenTour @42Gnome @kimmsue70 @RealDoctorT @cl1ntonserver @lemmabarkaloo @NewfMom29 @NotaDorR1 @TruthPyRate @ADirtyRottenDog @pookietooth @odktiger @Evry1H8sGrtzLOL @TastyMorsel6 @MurphyYuiko @theProgEqualist @LeAidan098 @1717mule @Polt223 @Jennie_SC1 @FemmeVoilet @LucaBra66424748 @_Kel_Varnsen_ @JackWhoElse @429jamesowens @instinctnaturel @Timeforfreespe1 @cow_cousin @MyChickenDinner @VtTbQW9s3xjPOow @TwoSides1Truth @SomeSis1 @LadyOfTheOcean1 @SnoJusticeBro @Aimhighffw I came here from Ireland.",
         "id": "1606437397582979073",
         "author_id": "1424486237289816064"
      },
      {
         "edit_history_tweet_ids": [
            "1606372480729419794"
         ],
         "text": "@xxx_porn_anal_1 kylie reverse cow ireland",
         "id": "1606372480729419794",
         "author_id": "1603056677967826944"
      },
      {
         "edit_history_tweet_ids": [
            "1606360856463294466"
         ],
         "text": "\"Meat Industry Ireland rejects idea of cow cull and want reduction in emissions to be delivered by magic\". https://t.co/VQJyjXeOIB",
         "id": "1606360856463294466",
         "author_id": "451740147"
      },
      {
         "edit_history_tweet_ids": [
            "1606354951634026502"
         ],
         "text": "Subscriber-only: Meat Industry Ireland rejects idea of cow cull and want reduction in emissions to be delivered by science. https://t.co/UdWEtq0C1P",
         "id": "1606354951634026502",
         "author_id": "133241378"
      },
      {
         "edit_history_tweet_ids": [
            "1606070678620278787"
         ],
         "text": "The \"Holee Cow\" Burger Challenge | Ireland's Biggest Burger https://t.co/leZF77Mgue via @YouTube",
         "id": "1606070678620278787",
         "author_id": "1147744140"
      },
      {
         "edit_history_tweet_ids": [
            "1606046300696285184"
         ],
         "text": "@RoughJustice7 @Noel_Hannan @brexit_sham @GodwinStan Northern Ireland a cash cow !  \nGive me a break, only if cows eat cash. \nIt will take £15 billion in 2022 to keep the population of NI in the luxury to which it has become accustomed, whilst the two biggest parties there bicker and drive their talented youth into disgusted exile.",
         "id": "1606046300696285184",
         "author_id": "1348714831453556737"
      },
      {
         "edit_history_tweet_ids": [
            "1605985785781501955"
         ],
         "text": "• Cow pregnancy scanning (65%*);\n• Artificial insemination (53%*);\n• Freezing branding (53%*).\n*Of Irish farms surveyed. \n\nRead the full report here: https://t.co/9yfAVq8oJT\n \n🚜If you are a farmer looking to develop your farm contact us today visit  💻https://t.co/hxvXteSRx0",
         "id": "1605985785781501955",
         "author_id": "1006464769682034688"
      },
      {
         "edit_history_tweet_ids": [
            "1605985629313056784"
         ],
         "text": "@Noel_Hannan @brexit_sham @GodwinStan Half of you are ashamed to be British it’s no wonder we shoot ourselves in the foot. As for the EU they block us every step of the way (look at the Northern Ireland border issue!) because they want their cash cow back.",
         "id": "1605985629313056784",
         "author_id": "1140736891404337152"
      },
      {
         "edit_history_tweet_ids": [
            "1605960624751529992"
         ],
         "text": "@ANTHONYDELANE40 @Independent_ie Really ?\n\nFree money you recon ?\n\nWhat's the public debt at the moment ?\n\nHow much of EU punlic debt was paid by Ireland  ?\n\nHow much EU money Ire got this year ?\n\nHow much contributions Ire paid to EU in last 10 years ?\n\nWhy cow shit on Irish fields is a problem ?",
         "id": "1605960624751529992",
         "author_id": "1243001951945711616"
      },
      {
         "edit_history_tweet_ids": [
            "1605895626708770816"
         ],
         "text": "@DeanoGriff1 Not his fault he was from Northern Ireland…..back then on muddy cow fields where defenders could 2 foot you from behind! Dont get a statue at Old Trafford for being average mate",
         "id": "1605895626708770816",
         "author_id": "302199139"
      },
      {
         "edit_history_tweet_ids": [
            "1605825760316428288"
         ],
         "text": "A cow and craggy Cliffs on the Aran Islands.   Photo by @marvelatireland @instaireland\n******   \nHow would you like more than 1 Million lovers of Ireland feasting their eyes on your business? - https://t.co/7Od7yFnGwq https://t.co/mKKQvFZp7u",
         "id": "1605825760316428288",
         "author_id": "1181678609095958528"
      },
      {
         "edit_history_tweet_ids": [
            "1605716476568096768"
         ],
         "text": "@KarlMartinIrl @rte Even Bolivia OLeary was on with her anecdote of Garrett mixing up Solidarnasc flag &amp; Cork Gaa, an abomination,GAA is sacred cow,no leader can rise without it,gaa banned Garrett from all Ireland final over vat on hurleys,but CJH was back next year &amp; vat still there! @SeanKellyMEP",
         "id": "1605716476568096768",
         "author_id": "194940707"
      },
      {
         "edit_history_tweet_ids": [
            "1605597401133228032"
         ],
         "text": "Landscape, Photography, Cow, Wildlife, Ennis, https://t.co/JzOrgGh2lY #photography #landscape #print #wallart #animal #cow #ireland #ennis @etsymktgtool https://t.co/O75hgNE80q",
         "id": "1605597401133228032",
         "author_id": "50731878"
      },
      {
         "edit_history_tweet_ids": [
            "1605545774388891648"
         ],
         "text": "Goddess vs Slave dinner 🍽 \n\n😂😈 Good, what i like to see. Goddess Xhesi deserves what she want to eat and you can use the loose change to go feed your worthless self. pathetic \n\nFindom • Dublin • Ireland • paypig • cash cow • Human ATM • Cashslave • Whalesub • sissy https://t.co/NmwpdNJ51D",
         "id": "1605545774388891648",
         "author_id": "1599932929584537602"
      },
      {
         "edit_history_tweet_ids": [
            "1605510270629171201"
         ],
         "text": "Are you going to see @DameStuffy in the Red Cow Inn #Panto? You can also see Dame Stuffy at @TheOutingFest, Valentines weekend 10th - 12th Feb 2023 😍\n\n#TheOutingFestival @ILoveGayDrag @Failte_Ireland @TourismIreland\n\nGet your tickets NOW! https://t.co/nHeEA38e7A https://t.co/RE3W5cfVMk",
         "id": "1605510270629171201",
         "author_id": "850393619034984449"
      },
      {
         "edit_history_tweet_ids": [
            "1605313030677749760"
         ],
         "text": "@wws_ireland What’s the kgs solids &amp; litres milk per cow, what’s the level of meal per cow, and how long does the herd receive buffer-feeding? Context is everything…..",
         "id": "1605313030677749760",
         "author_id": "243330723"
      },
      {
         "edit_history_tweet_ids": [
            "1605300034555334657"
         ],
         "text": "Rules: if you twitched you owe me €20. \nPay up Goon 💰 \n\nhttps://t.co/Nl0EqUBwaO\n😈\nhttps://t.co/4WRiR2mPNW\n\nFindom dublin | irish femdom | Ireland | paypig | cash meet | cash cow | cash slave | whalesub  | cuck | beta | finsub | Goddess | ass worship | drain | debt contract https://t.co/CjQMxxbC0Y",
         "id": "1605300034555334657",
         "author_id": "1599932929584537602"
      },
      {
         "edit_history_tweet_ids": [
            "1605285433696571411"
         ],
         "text": "You know what time it is. another day, another sub bringing me a boba 🧋 😌\nwhat sub will serve their Goddess tomorow ? 😴\n\nfindom ireland • Cash meet dublin • ireland • paypigs • human atm • slave • sub • paypiggie • cash cow • Domme • FindomGod • cuck • sissy https://t.co/bDPFD98bqd",
         "id": "1605285433696571411",
         "author_id": "1599932929584537602"
      }
   ],
   "meta": {
      "newest_id": "1607719593497305089",
      "oldest_id": "1605285433696571411",
      "result_count": 22
   }
}

In [6]:
json_response['data'][20]['text']

'Rules: if you twitched you owe me €20. \nPay up Goon 💰 \n\nhttps://t.co/Nl0EqUBwaO\n😈\nhttps://t.co/4WRiR2mPNW\n\nFindom dublin | irish femdom | Ireland | paypig | cash meet | cash cow | cash slave | whalesub  | cuck | beta | finsub | Goddess | ass worship | drain | debt contract https://t.co/CjQMxxbC0Y'

In [7]:
#!pip install twitter-stream.py

In [8]:
twitter_keys=f'''keys:
    access_token: {config["API_KEY"]}
    access_token_secret: {config["API_KEY_SECRET"]}
    bearer_token: {config["BEARER_TOKEN"]}
'''
with open("C:/Users/kftsu/.twitter-keys.yaml", "w") as file:
    file.write(twitter_keys)
with open("C:/Users/kftsu/.twitter_keys.yaml", "w") as file:
    file.write(twitter_keys)

In [9]:
import pandas as pd
#import json
import csv

In [10]:
with open ('Milk_ie.json', 'r', encoding='utf-8') as f:
    data= json.load(f)
    data = data['data']

with open ('Milk_ie.csv', 'w', encoding='utf-8') as f:
    fieldnames = data[0].keys()
    writer= csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for text in data:
        writer.writerow(text)

In [11]:
with open ('Cow_ie.json', 'r', encoding='utf-8') as f:
    data= json.load(f)
    data = data['data']

with open ('Cow_ie.csv', 'w', encoding='utf-8') as f:
    fieldnames = data[0].keys()
    writer= csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for text in data:
        writer.writerow(text)

I want to combine tweets about Milk, Dairy, and Cow in In Ireland.

In [12]:
import pandas as pd
import seaborn as sns
%config InlineBackend.figure_format = 'retina'
sns.set_context('talk')
import warnings
warnings.filterwarnings('ignore')
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [13]:
Milk_text_ie = pd.read_csv("Milk_ie.csv")
Cow_text_ie= pd.read_csv("Cow_ie.csv")

In [14]:
Milk_text_ie.head()

,text,id,author_id,edit_history_tweet_ids
0,"@fuckedupfoods As Someone From Ireland, We Can...",1607779060968574977,1253019792048631810,['1607779060968574977']
1,Pronouns: he/him/tat guy\r\nHeight: y'\r\nShoe...,1607749193900113922,1320733420545343488,['1607749193900113922']
2,@lidl_ireland milk chocolate coated pistachios...,1607739270844014592,565259157,['1607739270844014592']
3,"@davidtobin100 Agreed, a musician would never ...",1607722466578956290,2390486108,['1607722466578956290']
4,"Bonjour, I'm Meowkil Catson. I come from Irela...",1607650992119742465,1110398292695773184,['1607650992119742465']

In [15]:
Cow_text_ie.head()

,text,id,author_id,edit_history_tweet_ids
0,It is understood a cow was trapped in a slurry...,1607719593497305089,20687723,['1607719593497305089']
1,You know you're down home when you're having p...,1607698163133038594,431813199,['1607698163133038594']
2,Always. In 5th or 6th grade I did a school rep...,1606886570044309504,17845980,['1606886570044309504']
3,@7YRBitchLasagna @JenCages @MucusMucous @ADoub...,1606438931540606978,1300278104485756928,['1606438931540606978']
4,@JenCages @MucusMucous @RedStateJimy @ADouble7...,1606437397582979073,1424486237289816064,['1606437397582979073']

In [16]:
Milk_text_ie.shape
Cow_text_ie.shape

(34, 4)

(22, 4)

In [19]:
Milk_text_ie['Tweet']='Milk'
Milk_text_ie

,text,id,author_id,edit_history_tweet_ids,Tweet
0,"@fuckedupfoods As Someone From Ireland, We Can...",1607779060968574977,1253019792048631810,['1607779060968574977'],Milk
1,Pronouns: he/him/tat guy\r\nHeight: y'\r\nShoe...,1607749193900113922,1320733420545343488,['1607749193900113922'],Milk
2,@lidl_ireland milk chocolate coated pistachios...,1607739270844014592,565259157,['1607739270844014592'],Milk
3,"@davidtobin100 Agreed, a musician would never ...",1607722466578956290,2390486108,['1607722466578956290'],Milk
4,"Bonjour, I'm Meowkil Catson. I come from Irela...",1607650992119742465,1110398292695773184,['1607650992119742465'],Milk
5,A big thank you to those folks who voted in th...,1607638781007482880,2604207350,['1607638781007482880'],Milk
6,Incredible colonoscopic viualization of Trichu...,1607610546224005122,1565632325626388480,['1607610546224005122'],Milk
7,"Sup yo, I'm Captain Kitty. I come from Ireland...",1607484869407576064,1110398292695773184,['1607484869407576064'],Milk
8,"@CarlowWeather 😲😱🥶,... Did you manage to get t...",1607378640781598721,804584434993348608,['1607378640781598721'],Milk
9,@opheliamuses I've heard for years that doctor...,1607332811614347265,2329688173,['1607332811614347265'],Milk
10,"@withoutanecho Tbf after watching that film, m...",1607273980758474753,461771385,['1607273980758474753'],Milk
11,@egel34 @JoannaMWallace In NZ the tank is owne...,1607190221841653762,4129657521,['1607190221841653762'],Milk
12,@AlanBoyce47 @PeterZeihan We don't grow or imp...,1606947819600097281,1544261904201383937,['1606947819600097281'],Milk
13,🎄The Irish Spirit team would like to wish you ...,1606907741200678912,882061017638871041,['1606907741200678912'],Milk
14,"@VABVOX Same. I tried, but they are hideous. ...",1606721358490107904,3044871157,['1606721358490107904'],Milk
15,On Thursday evening I found out that in Irelan...,1606686850898268160,1272576450,['1606686850898268160'],Milk
16,Today We're Looking At The: Top 5 Foods From A...,1606642784424935426,1219276291326824454,['1606642784424935426'],Milk
17,The Milk Tray Man paid a visit earlier. \r\n#...,1606415771361501185,32635255,['1606415771361501185'],Milk
18,@RuisOlc @sitara68 I pray for the day Ireland ...,1606385932772511751,1177117794963460096,['1606385932772511751'],Milk
19,Northern Ireland - Horgan’s Delicatessen Suppl...,1606296143511650309,921197448885886977,['1606296143511650309'],Milk
20,"#family #mugs 9,99 https://t.co/5trcoyjqf4 #ce...",1606218228220317696,803910896842108928,['1606218228220317696'],Milk
21,"Howdly doodly, I'm Brandswaggle Cumberpunch. I...",1606208920707469312,1110398292695773184,['1606208920707469312'],Milk
22,"@crapbearddad Ah nice mate so you all set, sam...",1606056191360225284,1524089206645178372,['1606056191360225284'],Milk
23,@ju_and_the_cats Oh! That’s interesting… I had...,1606034116323020800,1877473106,['1606034116323020800'],Milk
24,"Heyo, I'm Brandswaggle Cumberpunch. I come fro...",1605982422251601920,1110398292695773184,['1605982422251601920'],Milk
25,@DaiJordan1 @GBNEWS @Nigel_Farage From what I ...,1605952729154605057,7349062,['1605952729154605057'],Milk
26,@politicsIN @irish_news Because he tried to mi...,1605937011755401216,514788343,['1605937011755401216'],Milk
27,The first of two loads of incalf and in milk c...,1605887245793120258,1889991276,['1605887245793120258'],Milk
28,A bulk milk tank study to detect evidence of s...,1605860331406102528,900590952196198400,['1605860331406102528'],Milk
29,@sligojord American’s do not want to know. Pro...,1605787258103398400,1081334295849889793,['1605787258103398400'],Milk
30,@texans945 @StrawHatNate27 @Milk_and_Honey5 @Q...,1605784369796464640,1459117770994589696,['1605784369796464640'],Milk
31,@GameOnClimate @farmersjournal Ireland is one ...,1605663786521747472,1342025170253475840,['1605663786521747472'],Milk
32,I wonder if the UK are Ireland are below the r...,1605518527275966464,2733713380,['1605518527275966464'],Milk
33,@wws_ireland What’s the kgs solids &amp; litre...,1605313030677749760,243330723,['1605313030677749760'],Milk

In [20]:
Cow_text_ie['Tweet']='Cow'
Cow_text_ie

,text,id,author_id,edit_history_tweet_ids,Tweet
0,It is understood a cow was trapped in a slurry...,1607719593497305089,20687723,['1607719593497305089'],Cow
1,You know you're down home when you're having p...,1607698163133038594,431813199,['1607698163133038594'],Cow
2,Always. In 5th or 6th grade I did a school rep...,1606886570044309504,17845980,['1606886570044309504'],Cow
3,@7YRBitchLasagna @JenCages @MucusMucous @ADoub...,1606438931540606978,1300278104485756928,['1606438931540606978'],Cow
4,@JenCages @MucusMucous @RedStateJimy @ADouble7...,1606437397582979073,1424486237289816064,['1606437397582979073'],Cow
5,@xxx_porn_anal_1 kylie reverse cow ireland,1606372480729419794,1603056677967826944,['1606372480729419794'],Cow
6,"""Meat Industry Ireland rejects idea of cow cul...",1606360856463294466,451740147,['1606360856463294466'],Cow
7,Subscriber-only: Meat Industry Ireland rejects...,1606354951634026502,133241378,['1606354951634026502'],Cow
8,"The ""Holee Cow"" Burger Challenge | Ireland's B...",1606070678620278787,1147744140,['1606070678620278787'],Cow
9,@RoughJustice7 @Noel_Hannan @brexit_sham @Godw...,1606046300696285184,1348714831453556737,['1606046300696285184'],Cow
10,• Cow pregnancy scanning (65%*);\r\n• Artifici...,1605985785781501955,1006464769682034688,['1605985785781501955'],Cow
11,@Noel_Hannan @brexit_sham @GodwinStan Half of ...,1605985629313056784,1140736891404337152,['1605985629313056784'],Cow
12,@ANTHONYDELANE40 @Independent_ie Really ?\r\n\...,1605960624751529992,1243001951945711616,['1605960624751529992'],Cow
13,@DeanoGriff1 Not his fault he was from Norther...,1605895626708770816,302199139,['1605895626708770816'],Cow
14,A cow and craggy Cliffs on the Aran Islands. ...,1605825760316428288,1181678609095958528,['1605825760316428288'],Cow
15,@KarlMartinIrl @rte Even Bolivia OLeary was on...,1605716476568096768,194940707,['1605716476568096768'],Cow
16,"Landscape, Photography, Cow, Wildlife, Ennis, ...",1605597401133228032,50731878,['1605597401133228032'],Cow
17,"Goddess vs Slave dinner 🍽 \r\n\r\n😂😈 Good, wha...",1605545774388891648,1599932929584537602,['1605545774388891648'],Cow
18,Are you going to see @DameStuffy in the Red Co...,1605510270629171201,850393619034984449,['1605510270629171201'],Cow
19,@wws_ireland What’s the kgs solids &amp; litre...,1605313030677749760,243330723,['1605313030677749760'],Cow
20,Rules: if you twitched you owe me €20. \r\nPay...,1605300034555334657,1599932929584537602,['1605300034555334657'],Cow
21,"You know what time it is. another day, another...",1605285433696571411,1599932929584537602,['1605285433696571411'],Cow

In [32]:
Milk_Cow_Tweets = pd.merge(Milk_text_ie, Cow_text_ie, how="outer")

In [33]:
Milk_Cow_Tweets.shape

(56, 5)

In [34]:
Milk_Cow_Tweets

,text,id,author_id,edit_history_tweet_ids,Tweet
0,"@fuckedupfoods As Someone From Ireland, We Can...",1607779060968574977,1253019792048631810,['1607779060968574977'],Milk
1,Pronouns: he/him/tat guy\r\nHeight: y'\r\nShoe...,1607749193900113922,1320733420545343488,['1607749193900113922'],Milk
2,@lidl_ireland milk chocolate coated pistachios...,1607739270844014592,565259157,['1607739270844014592'],Milk
3,"@davidtobin100 Agreed, a musician would never ...",1607722466578956290,2390486108,['1607722466578956290'],Milk
4,"Bonjour, I'm Meowkil Catson. I come from Irela...",1607650992119742465,1110398292695773184,['1607650992119742465'],Milk
5,A big thank you to those folks who voted in th...,1607638781007482880,2604207350,['1607638781007482880'],Milk
6,Incredible colonoscopic viualization of Trichu...,1607610546224005122,1565632325626388480,['1607610546224005122'],Milk
7,"Sup yo, I'm Captain Kitty. I come from Ireland...",1607484869407576064,1110398292695773184,['1607484869407576064'],Milk
8,"@CarlowWeather 😲😱🥶,... Did you manage to get t...",1607378640781598721,804584434993348608,['1607378640781598721'],Milk
9,@opheliamuses I've heard for years that doctor...,1607332811614347265,2329688173,['1607332811614347265'],Milk
10,"@withoutanecho Tbf after watching that film, m...",1607273980758474753,461771385,['1607273980758474753'],Milk
11,@egel34 @JoannaMWallace In NZ the tank is owne...,1607190221841653762,4129657521,['1607190221841653762'],Milk
12,@AlanBoyce47 @PeterZeihan We don't grow or imp...,1606947819600097281,1544261904201383937,['1606947819600097281'],Milk
13,🎄The Irish Spirit team would like to wish you ...,1606907741200678912,882061017638871041,['1606907741200678912'],Milk
14,"@VABVOX Same. I tried, but they are hideous. ...",1606721358490107904,3044871157,['1606721358490107904'],Milk
15,On Thursday evening I found out that in Irelan...,1606686850898268160,1272576450,['1606686850898268160'],Milk
16,Today We're Looking At The: Top 5 Foods From A...,1606642784424935426,1219276291326824454,['1606642784424935426'],Milk
17,The Milk Tray Man paid a visit earlier. \r\n#...,1606415771361501185,32635255,['1606415771361501185'],Milk
18,@RuisOlc @sitara68 I pray for the day Ireland ...,1606385932772511751,1177117794963460096,['1606385932772511751'],Milk
19,Northern Ireland - Horgan’s Delicatessen Suppl...,1606296143511650309,921197448885886977,['1606296143511650309'],Milk
20,"#family #mugs 9,99 https://t.co/5trcoyjqf4 #ce...",1606218228220317696,803910896842108928,['1606218228220317696'],Milk
21,"Howdly doodly, I'm Brandswaggle Cumberpunch. I...",1606208920707469312,1110398292695773184,['1606208920707469312'],Milk
22,"@crapbearddad Ah nice mate so you all set, sam...",1606056191360225284,1524089206645178372,['1606056191360225284'],Milk
23,@ju_and_the_cats Oh! That’s interesting… I had...,1606034116323020800,1877473106,['1606034116323020800'],Milk
24,"Heyo, I'm Brandswaggle Cumberpunch. I come fro...",1605982422251601920,1110398292695773184,['1605982422251601920'],Milk
25,@DaiJordan1 @GBNEWS @Nigel_Farage From what I ...,1605952729154605057,7349062,['1605952729154605057'],Milk
26,@politicsIN @irish_news Because he tried to mi...,1605937011755401216,514788343,['1605937011755401216'],Milk
27,The first of two loads of incalf and in milk c...,1605887245793120258,1889991276,['1605887245793120258'],Milk
28,A bulk milk tank study to detect evidence of s...,1605860331406102528,900590952196198400,['1605860331406102528'],Milk
29,@sligojord American’s do not want to know. Pro...,1605787258103398400,1081334295849889793,['1605787258103398400'],Milk
30,@texans945 @StrawHatNate27 @Milk_and_Honey5 @Q...,1605784369796464640,1459117770994589696,['1605784369796464640'],Milk
31,@GameOnClimate @farmersjournal Ireland is one ...,1605663786521747472,1342025170253475840,['1605663786521747472'],Milk
32,I wonder if the UK are Ireland are below the r...,1605518527275966464,2733713380,['1605518527275966464'],Milk
33,@wws_ireland What’s the kgs solids &amp; litre...,1605313030677749760,243330723,['1605313030677749760'],Milk
34,It is understood a cow was trapped in a slurry...,1607719593497305089,20687723,['1607719593497305089'],Cow
35,You know you're down home when you're having p...,1607698163133038594,431813199,['1607698163133038594'],Cow
36,Always. In 5th or 6th grade I did a school rep...,1606886570044309504,17845980,['1606886570044309504'],Cow
37,@7YRBitchLasagna @JenCages @MucusMucous @ADoub...,1606438931540606978,1300278104485756928,['1606438931540606978'],Cow
38,@JenCages @MucusMucous @RedStateJimy @ADouble7...,1606437397582979073,1424486237289816064,['1606437397582979073'],Cow
39,@xxx_porn_anal_1 kylie reverse cow ireland,1606372480729419794,1603056677967826944,['1606372480729419794'],Cow
40,"""Meat Industry Ireland rejects idea of cow cul...",1606360856463294466,451740147,['1606360856463294466'],Cow
41,Subscriber-only: Meat Industry Ireland rejects...,1606354951634026502,133241378,['1606354951634026502'],Cow
42,"The ""Holee Cow"" Burger Challenge | Ireland's B...",1606070678620278787,1147744140,['1606070678620278787'],Cow
43,@RoughJustice7 @Noel_Hannan @brexit_sham @Godw...,1606046300696285184,1348714831453556737,['1606046300696285184'],Cow
44,• Cow pregnancy scanning (65%*);\r\n• Artifici...,1605985785781501955,1006464769682034688,['1605985785781501955'],Cow
45,@Noel_Hannan @brexit_sham @GodwinStan Half of ...,1605985629313056784,1140736891404337152,['1605985629313056784'],Cow
46,@ANTHONYDELANE40 @Independent_ie Really ?\r\n\...,1605960624751529992,1243001951945711616,['1605960624751529992'],Cow
47,@DeanoGriff1 Not his fault he was from Norther...,1605895626708770816,302199139,['1605895626708770816'],Cow
48,A cow and craggy Cliffs on the Aran Islands. ...,1605825760316428288,1181678609095958528,['1605825760316428288'],Cow
49,@KarlMartinIrl @rte Even Bolivia OLeary was on...,1605716476568096768,194940707,['1605716476568096768'],Cow
50,"Landscape, Photography, Cow, Wildlife, Ennis, ...",1605597401133228032,50731878,['1605597401133228032'],Cow
51,"Goddess vs Slave dinner 🍽 \r\n\r\n😂😈 Good, wha...",1605545774388891648,1599932929584537602,['1605545774388891648'],Cow
52,Are you going to see @DameStuffy in the Red Co...,1605510270629171201,850393619034984449,['1605510270629171201'],Cow
53,@wws_ireland What’s the kgs solids &amp; litre...,1605313030677749760,243330723,['1605313030677749760'],Cow
54,Rules: if you twitched you owe me €20. \r\nPay...,1605300034555334657,1599932929584537602,['1605300034555334657'],Cow
55,"You know what time it is. another day, another...",1605285433696571411,1599932929584537602,['1605285433696571411'],Cow

In [35]:
Milk_Cow_Tweets.to_excel('Milk_Cow_Tweets.xlsx', index = False)

### Data for Testing

In [47]:
with open ('Dairy_ie.json', 'r', encoding='utf-8') as f:
    data= json.load(f)
    data = data['data']
    
with open ('Dairy_ie.csv', 'w', encoding='utf-8') as f:
    fieldnames = data[0].keys()
    writer= csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for text in data:
        writer.writerow(text);

42

168

300

258

347

300

253

343

332

351

369

253

294

184

300

220

205

260

239

307

300

371

212

362

204

211

363

265

401

310